### ISSUE TITLE
Plugin settings do not update when `settingOptions` is changed

### ISSUE THREAD

**Issue by zaneshaw** [christopherwk210/tmcp#1]
When any of the values of `settingOptions` in `tmcp.addSettings()` is changed (aside from `text`), the corresponding object in the settings.json file in Roaming does not update (Even after a full reload). This issue really only comes up in plugin development and not during normal use of TMCP.

Should we remove these entries but preserve the value on a full reload?

**Comment by christopherwk210** [comment]
Good catch, addressed in bd9a4d3. When `tmcp.addSetting()` is called it will now overwrite existing fields (except `value`) for settings that were already added.

Something interesting I found is that `electron-settings` seems to be a bit finicky and doesn't always commit these changes to the file on the first call. I haven't been able to determine the cause, but I guess it might be related to setting a deeply nested object. Worth solving eventually, but not a deal breaker because the UI correctly updates. We can just full reload the application again if we need to during development, shouldn't come up during regular use.

**Comment by zaneshaw** [comment]
Nice. Thanks for fixing this so quick!
